version: '3'
services:
    adminer:
        image: adminer:latest
        restart: always
        ports:
          - 3037:8080
        environment:
          ADMINER_DEFAULT_SERVER: "mysql"
          ADMINER_DESIGN: "hydra"
        networks:
          - slides

    postgres:
        image: postgres
        restart: always
        ports:
            - '${DATABASE_PORT:-3306}:5432'
        environment:
            POSTGRES_DB: '${DATABASE_NAME}'
            POSTGRES_USER: '${DATABASE_USERNAME}'
            POSTGRES_PASSWORD: '${DATABASE_PASSWORD}'
            PG_TRUST_LOCALNET: true
        volumes:
            - 'pgVol:/var/lib/postgresql/data'
        networks:
            - slides
networks:
    slides:
        driver: bridge
volumes:
    pgVol:
        driver: local
